kind: pipeline
type: kubernetes
name: RedisBuild

- name: lint chart
  image: pelotech/drone-helm3
  settings:
    mode: lint
    chart: ./
    value_files: ./values.yaml

- name: Deploy Redis.
  image: pelotech/drone-helm3
  namespace: trivy-demo
  settings:
    mode: upgrade
    chart: ./
    release: redis-server
    value_files: ./values.yaml
  environment:
    kube_api_server:
      from_secret: k8s_server
    kube_token:
      from_secret: k8s_token
    kube_certificate:
      from_secret: k8s_crt
    kube_service_account:
      from_secret: k8s_sa