kind: pipeline
type: kubernetes
name: RedisBuild

steps:
- name: lint chart
  image: pelotech/drone-helm3
  settings:
    mode: lint
    chart: ./
    value_files: ./values.yaml

- name: Deploy Redis dry-run.
  image: pelotech/drone-helm3
  settings:
    namespace: trivy-redis
    mode: upgrade
    chart: ./
    release: redis-server
    value_files: ./values.yaml
    dry-run: --dry-run
  environment:
    API_SERVER:
      from_secret: k8s_server
    KUBERNETES_TOKEN:
      from_secret: k8s_token
    KUBE_CERTIFICATE:
      from_secret: k8s_crt
    kube_service_account:
      from_secret: k8s_sa

- name: Deploy Redis.
  image: pelotech/drone-helm3
  settings:
    namespace: trivy-redis
    mode: upgrade
    chart: ./
    release: redis-server
    value_files: ./values.yaml
  environment:
    API_SERVER:
      from_secret: k8s_server
    KUBERNETES_TOKEN:
      from_secret: k8s_token
    KUBE_CERTIFICATE:
      from_secret: k8s_crt
    kube_service_account:
      from_secret: k8s_sa